import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
    Download,
    CheckCircle,
    ChevronLeft,
    ChevronRight,
    Table2,
    BarChart2,
    FileSpreadsheet,
    FileImage,
    FileText,
    FileBarChart,
    ChevronDown,

} from 'lucide-react';
import { useRef, useState } from 'react';
import { VegaEmbed } from 'react-vega';
import { toast } from 'sonner';
import type { QueryResult } from '../../types';

interface ResultsTableProps {
    result: QueryResult;
    chartImage?: string;
    chartSpec?: any;
}

const ResultsTable = ({ result, chartImage, chartSpec }: ResultsTableProps) => {
    const [currentPage, setCurrentPage] = useState(1);
    const [view, setView] = useState<'table' | 'chart'>('table');
    const tableRef = useRef<HTMLDivElement>(null);
    const chartRef = useRef<HTMLDivElement>(null);

    const itemsPerPage = 10;
    const totalPages = Math.ceil(result.rows.length / itemsPerPage);

    // ── Export: CSV ──────────────────────────────────────────────────────────
    const exportCSV = () => {
        const csv = [
            result.columns.join(','),
            ...result.rows.map(row =>
                Array.isArray(row)
                    ? row.map((cell: any) => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(',')
                    : result.columns.map(col => `"${String((row as any)[col] ?? '').replace(/"/g, '""')}"`).join(',')
            )
        ].join('\n');
        const blob = new Blob([csv], { type: 'text/csv' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'query_results.csv';
        a.click();
        URL.revokeObjectURL(url);
        toast.success('CSV exported successfully');
    };

    // ── Export: Table as PDF ──────────────────────────────────────────────────
    const exportTablePDF = async () => {
        try {
            const { default: jsPDF } = await import('jspdf');
            const { default: html2canvas } = await import('html2canvas');

            if (!tableRef.current) {
                toast.error('Table not found');
                return;
            }

            toast.loading('Generating Table PDF…');
            const canvas = await html2canvas(tableRef.current, {
                scale: 2,
                useCORS: true,
                backgroundColor: '#ffffff',
            });

            const imgData = canvas.toDataURL('image/png');
            const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
            const pdfW = pdf.internal.pageSize.getWidth();
            const pdfH = (canvas.height * pdfW) / canvas.width;

            // Header strip
            pdf.setFillColor(139, 92, 246);
            pdf.rect(0, 0, pdfW, 12, 'F');
            pdf.setTextColor(255, 255, 255);
            pdf.setFontSize(11);
            pdf.setFont('helvetica', 'bold');
            pdf.text('Query Results — Table', 10, 8);
            pdf.setFontSize(8);
            pdf.text(`${result.rowCount} rows · Generated ${new Date().toLocaleString()}`, pdfW - 10, 8, { align: 'right' });

            pdf.addImage(imgData, 'PNG', 0, 14, pdfW, pdfH);

            // Footer
            pdf.setTextColor(150, 150, 150);
            pdf.setFontSize(7);
            pdf.setFont('helvetica', 'normal');
            pdf.text('Generated by NLP Database Chatbot', 10, pdf.internal.pageSize.getHeight() - 4);

            pdf.save('table_results.pdf');
            toast.dismiss();
            toast.success('Table PDF downloaded!');
        } catch (err) {
            toast.dismiss();
            toast.error('Failed to generate Table PDF');
            console.error(err);
        }
    };

    // ── Export: Chart as PDF ─────────────────────────────────────────────────
    const exportChartPDF = async () => {
        if (!chartImage && !chartRef.current) {
            toast.error('No chart available. Switch to Chart view first.');
            return;
        }
        try {
            const { default: jsPDF } = await import('jspdf');
            const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
            const pdfW = pdf.internal.pageSize.getWidth();
            const pdfH = pdf.internal.pageSize.getHeight();

            // Header
            pdf.setFillColor(139, 92, 246);
            pdf.rect(0, 0, pdfW, 12, 'F');
            pdf.setTextColor(255, 255, 255);
            pdf.setFontSize(11);
            pdf.setFont('helvetica', 'bold');
            pdf.text('Query Results — Chart', 10, 8);
            pdf.setFontSize(8);
            pdf.text(`Generated ${new Date().toLocaleString()}`, pdfW - 10, 8, { align: 'right' });

            toast.loading('Generating Chart PDF…');

            if (chartRef.current) {
                // Interactive Vega chart → render via html2canvas
                const { default: html2canvas } = await import('html2canvas');
                const canvas = await html2canvas(chartRef.current, {
                    scale: 2, useCORS: true, backgroundColor: '#ffffff',
                });
                const imgData = canvas.toDataURL('image/png');
                const imgH = (canvas.height * pdfW) / canvas.width;
                pdf.addImage(imgData, 'PNG', 0, 14, pdfW, Math.min(imgH, pdfH - 20));
            } else if (chartImage) {
                // Static Matplotlib PNG → directly embed
                const img = new Image();
                img.src = `data:image/png;base64,${chartImage}`;
                await new Promise(r => { img.onload = r; });
                const aspect = img.naturalHeight / img.naturalWidth;
                const imgH = Math.min(pdfW * aspect, pdfH - 20);
                const imgY = 14 + (pdfH - 20 - imgH) / 2;
                pdf.addImage(`data:image/png;base64,${chartImage}`, 'PNG', 0, imgY, pdfW, imgH);
            }

            // Footer
            pdf.setTextColor(150, 150, 150);
            pdf.setFontSize(7);
            pdf.setFont('helvetica', 'normal');
            pdf.text('Generated by NLP Database Chatbot', 10, pdfH - 4);

            pdf.save('chart_results.pdf');
            toast.dismiss();
            toast.success('Chart PDF downloaded!');
        } catch (err) {
            toast.dismiss();
            toast.error('Failed to generate Chart PDF');
            console.error(err);
        }
    };

    // ── Export: Full Report (Chart + Table) as single PDF ─────────────────────
    const exportFullReportPDF = async () => {
        try {
            const { default: jsPDF } = await import('jspdf');
            const { default: html2canvas } = await import('html2canvas');

            toast.loading('Generating Full Report PDF…');

            const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
            const pdfW = pdf.internal.pageSize.getWidth();
            const pdfH = pdf.internal.pageSize.getHeight();
            const margin = 10;
            const contentW = pdfW - margin * 2;
            let cursorY = 0;

            // ── Helper: add header strip to current page ──
            const addHeader = (subtitle: string) => {
                pdf.setFillColor(139, 92, 246);
                pdf.rect(0, 0, pdfW, 14, 'F');
                pdf.setTextColor(255, 255, 255);
                pdf.setFontSize(12);
                pdf.setFont('helvetica', 'bold');
                pdf.text('Query Results — Full Report', margin, 9);
                pdf.setFontSize(8);
                pdf.setFont('helvetica', 'normal');
                pdf.text(subtitle, pdfW - margin, 9, { align: 'right' });
                cursorY = 18;
            };

            // ── Helper: add footer to current page ──
            const addFooter = () => {
                pdf.setTextColor(150, 150, 150);
                pdf.setFontSize(7);
                pdf.setFont('helvetica', 'normal');
                pdf.text('Generated by NLP Database Chatbot', margin, pdfH - 4);
                pdf.text(
                    `Page ${pdf.getNumberOfPages()}`,
                    pdfW - margin, pdfH - 4,
                    { align: 'right' }
                );
            };

            // ── PAGE 1: Chart ──
            addHeader(`${result.rowCount} rows · ${new Date().toLocaleString()}`);

            // Section title
            pdf.setFillColor(245, 243, 255);
            pdf.roundedRect(margin, cursorY, contentW, 8, 2, 2, 'F');
            pdf.setTextColor(109, 40, 217);
            pdf.setFontSize(9);
            pdf.setFont('helvetica', 'bold');
            pdf.text('📊  Chart Visualization', margin + 4, cursorY + 5.5);
            cursorY += 12;

            let chartRendered = false;

            if (chartRef.current) {
                // Interactive Vega chart → render via html2canvas
                const canvas = await html2canvas(chartRef.current, {
                    scale: 2, useCORS: true, backgroundColor: '#ffffff',
                });
                const imgData = canvas.toDataURL('image/png');
                const imgH = (canvas.height * contentW) / canvas.width;
                const fitH = Math.min(imgH, pdfH - cursorY - 14);
                pdf.addImage(imgData, 'PNG', margin, cursorY, contentW, fitH);
                chartRendered = true;
            } else if (chartImage) {
                // Static Matplotlib PNG
                const img = new Image();
                img.src = `data:image/png;base64,${chartImage}`;
                await new Promise(r => { img.onload = r; });
                const aspect = img.naturalHeight / img.naturalWidth;
                const imgH = Math.min(contentW * aspect, pdfH - cursorY - 14);
                pdf.addImage(`data:image/png;base64,${chartImage}`, 'PNG', margin, cursorY, contentW, imgH);
                chartRendered = true;
            }

            if (!chartRendered) {
                pdf.setTextColor(160, 160, 160);
                pdf.setFontSize(10);
                pdf.setFont('helvetica', 'italic');
                pdf.text('No chart available for this query.', margin + 4, cursorY + 10);
            }

            addFooter();

            // ── PAGE 2+: Data Table ──
            // Build a temporary full table (all rows) off-screen and capture it
            const tempContainer = document.createElement('div');
            tempContainer.style.position = 'absolute';
            tempContainer.style.left = '-9999px';
            tempContainer.style.top = '0';
            tempContainer.style.width = '1200px';
            tempContainer.style.background = '#ffffff';
            tempContainer.style.padding = '16px';

            // Section heading inside the rendered block
            const heading = document.createElement('div');
            heading.style.cssText = 'background:#f5f3ff;border-radius:6px;padding:6px 14px;margin-bottom:12px;font-size:13px;font-weight:700;color:#6d28d9;';
            heading.textContent = '📋  Data Table';
            tempContainer.appendChild(heading);

            const table = document.createElement('table');
            table.style.cssText = 'width:100%;border-collapse:collapse;font-size:12px;font-family:system-ui,sans-serif;';

            // Header
            const thead = document.createElement('thead');
            const hRow = document.createElement('tr');
            result.columns.forEach(col => {
                const th = document.createElement('th');
                th.textContent = col;
                th.style.cssText = 'padding:8px 12px;text-align:left;background:#f8fafc;border-bottom:2px solid #e2e8f0;font-weight:600;color:#334155;white-space:nowrap;';
                hRow.appendChild(th);
            });
            thead.appendChild(hRow);
            table.appendChild(thead);

            // Body — ALL rows
            const tbody = document.createElement('tbody');
            result.rows.forEach((row, rIdx) => {
                const tr = document.createElement('tr');
                tr.style.cssText = rIdx % 2 === 0 ? 'background:#ffffff;' : 'background:#f8fafc;';
                result.columns.forEach((col, cIdx) => {
                    const td = document.createElement('td');
                    td.textContent = getCellValue(row, col, cIdx);
                    td.style.cssText = 'padding:6px 12px;border-bottom:1px solid #f1f5f9;color:#475569;white-space:nowrap;';
                    tr.appendChild(td);
                });
                tbody.appendChild(tr);
            });
            table.appendChild(tbody);
            tempContainer.appendChild(table);

            // Row count badge
            const badge = document.createElement('div');
            badge.style.cssText = 'margin-top:10px;font-size:11px;color:#94a3b8;text-align:right;';
            badge.textContent = `Total: ${result.rowCount} rows · Generated ${new Date().toLocaleString()}`;
            tempContainer.appendChild(badge);

            document.body.appendChild(tempContainer);

            const tableCanvas = await html2canvas(tempContainer, {
                scale: 2, useCORS: true, backgroundColor: '#ffffff',
            });

            document.body.removeChild(tempContainer);

            const tableImgFullH = (tableCanvas.height * contentW) / tableCanvas.width;

            // Paginate the table image across however many pages it needs
            const usableH = pdfH - 18 - 10; // header area + footer area
            let imgOffsetY = 0;

            while (imgOffsetY < tableImgFullH) {
                pdf.addPage();
                addHeader(`${result.rowCount} rows · Data Table`);

                const sliceH = Math.min(usableH, tableImgFullH - imgOffsetY);

                // We crop part of the source image using a temporary canvas
                const sliceCanvas = document.createElement('canvas');
                const scaleFactor = tableCanvas.width / contentW;
                sliceCanvas.width = tableCanvas.width;
                sliceCanvas.height = sliceH * scaleFactor;
                const ctx = sliceCanvas.getContext('2d')!;
                ctx.drawImage(
                    tableCanvas,
                    0, imgOffsetY * scaleFactor,             // source x, y
                    tableCanvas.width, sliceH * scaleFactor, // source w, h
                    0, 0,                                     // dest x, y
                    sliceCanvas.width, sliceCanvas.height     // dest w, h
                );

                pdf.addImage(sliceCanvas.toDataURL('image/png'), 'PNG', margin, cursorY, contentW, sliceH);
                addFooter();
                imgOffsetY += sliceH;
            }

            pdf.save('full_report.pdf');
            toast.dismiss();
            toast.success('Full Report PDF downloaded!');
        } catch (err) {
            toast.dismiss();
            toast.error('Failed to generate Full Report PDF');
            console.error(err);
        }
    };

    // ── Pagination ────────────────────────────────────────────────────────────
    const handlePageChange = (newPage: number) => {
        if (newPage >= 1 && newPage <= totalPages) setCurrentPage(newPage);
    };

    const currentRows = result.rows.slice(
        (currentPage - 1) * itemsPerPage,
        currentPage * itemsPerPage
    );

    const getCellValue = (row: any, col: string, colIdx: number): string => {
        let val: any;
        if (Array.isArray(row)) {
            val = row[colIdx];
        } else {
            val = (row as Record<string, any>)[col];
        }

        if (val == null) return '';

        const colLower = col.toLowerCase();
        if (typeof val === 'number' && (colLower.includes('oee') || colLower.includes('%') || colLower.includes('rate') || colLower.includes('percentage'))) {
            return `${val.toFixed(2)}%`;
        }

        return String(val);
    };

    const hasChart = !!(chartImage || chartSpec);

    return (
        <div className="mt-3">
            {/* ── Top bar ── */}
            <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2">
                    <Badge variant="secondary" className="text-xs">
                        <CheckCircle className="w-3 h-3 mr-1" />
                        {result.rowCount} rows
                    </Badge>
                    <span className="text-xs text-slate-500">{result.executionTime}s</span>
                </div>

                <div className="flex items-center gap-1.5">
                    {/* Table / Chart toggle — only shown when a chart exists */}
                    {hasChart && (
                        <div className="flex bg-slate-100 rounded-lg p-0.5 mr-1 shadow-inner">
                            <Button
                                variant="ghost"
                                size="sm"
                                className={`h-6 px-2.5 gap-1.5 text-[11px] rounded-md transition-all duration-200 ${view === 'table'
                                    ? 'bg-white text-slate-900 shadow-sm font-semibold'
                                    : 'text-slate-500 hover:text-slate-700'
                                    }`}
                                onClick={() => setView('table')}
                            >
                                <Table2 className="w-3.5 h-3.5" /> Table
                            </Button>
                            <Button
                                variant="ghost"
                                size="sm"
                                className={`h-6 px-2.5 gap-1.5 text-[11px] rounded-md transition-all duration-200 ${view === 'chart'
                                    ? 'bg-white text-purple-700 shadow-sm font-semibold'
                                    : 'text-slate-500 hover:text-slate-700'
                                    }`}
                                onClick={() => setView('chart')}
                            >
                                <BarChart2 className="w-3.5 h-3.5" /> Chart
                            </Button>
                        </div>
                    )}

                    {/* ── Download dropdown ── */}
                    <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                            <Button variant="outline" size="sm" className="h-7 text-xs gap-1 shadow-sm hover:bg-slate-50">
                                <Download className="w-3 h-3" />
                                Download
                                <ChevronDown className="w-3 h-3 opacity-60" />
                            </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end" className="w-52 shadow-lg border-slate-200">
                            <DropdownMenuLabel className="text-[10px] text-slate-400 uppercase tracking-widest font-semibold px-3 py-1">
                                Export Options
                            </DropdownMenuLabel>
                            <DropdownMenuSeparator />

                            {/* CSV */}
                            <DropdownMenuItem onClick={exportCSV} className="gap-2.5 cursor-pointer">
                                <div className="w-7 h-7 rounded-md bg-green-50 flex items-center justify-center shrink-0">
                                    <FileSpreadsheet className="w-3.5 h-3.5 text-green-600" />
                                </div>
                                <div>
                                    <div className="text-xs font-medium text-slate-800">Export CSV</div>
                                    <div className="text-[10px] text-slate-400">Raw data for Excel</div>
                                </div>
                            </DropdownMenuItem>

                            {/* Table PDF */}
                            <DropdownMenuItem onClick={exportTablePDF} className="gap-2.5 cursor-pointer">
                                <div className="w-7 h-7 rounded-md bg-blue-50 flex items-center justify-center shrink-0">
                                    <FileText className="w-3.5 h-3.5 text-blue-600" />
                                </div>
                                <div>
                                    <div className="text-xs font-medium text-slate-800">Download Table PDF</div>
                                    <div className="text-[10px] text-slate-400">Current table as PDF</div>
                                </div>
                            </DropdownMenuItem>

                            {/* Chart PDF — only if chart is available */}
                            {hasChart && (
                                <DropdownMenuItem onClick={exportChartPDF} className="gap-2.5 cursor-pointer">
                                    <div className="w-7 h-7 rounded-md bg-purple-50 flex items-center justify-center shrink-0">
                                        <FileImage className="w-3.5 h-3.5 text-purple-600" />
                                    </div>
                                    <div>
                                        <div className="text-xs font-medium text-slate-800">Download Chart PDF</div>
                                        <div className="text-[10px] text-slate-400">Visualization as PDF</div>
                                    </div>
                                </DropdownMenuItem>
                            )}

                            <DropdownMenuSeparator />

                            {/* Full Report PDF — Chart + Table combined */}
                            <DropdownMenuItem onClick={exportFullReportPDF} className="gap-2.5 cursor-pointer">
                                <div className="w-7 h-7 rounded-md bg-gradient-to-br from-purple-50 to-blue-50 flex items-center justify-center shrink-0">
                                    <FileBarChart className="w-3.5 h-3.5 text-indigo-600" />
                                </div>
                                <div>
                                    <div className="text-xs font-medium text-slate-800">Download Full Report</div>
                                    <div className="text-[10px] text-slate-400">Chart + Table in one PDF</div>
                                </div>
                            </DropdownMenuItem>
                        </DropdownMenuContent>
                    </DropdownMenu>
                </div>
            </div>

            {/* ── Chart view ── */}
            {view === 'chart' && hasChart ? (
                <div className="rounded-xl overflow-hidden border border-slate-100 shadow-md bg-white animate-in fade-in zoom-in duration-300">
                    <div className="flex items-center gap-2 px-4 py-2.5 border-b border-slate-100 bg-slate-50/60">
                        <BarChart2 className="w-4 h-4 text-purple-500" />
                        <span className="text-xs font-semibold text-slate-700">
                            Visualization
                        </span>
                        <span className="ml-auto text-[10px] text-slate-400 font-medium">Statistical Insights</span>
                    </div>
                    <div ref={chartRef} className="p-4 flex flex-col justify-center bg-white min-h-[350px]">
                        {chartImage ? (
                            <img
                                src={`data:image/png;base64,${chartImage}`}
                                alt="Data visualization with statistical annotations"
                                className="max-w-full h-auto rounded-lg mx-auto"
                                style={{ maxHeight: '420px', objectFit: 'contain' }}
                            />
                        ) : chartSpec ? (
                            <div className="w-full h-full min-h-[300px]">
                                <VegaEmbed
                                    spec={chartSpec}
                                    options={{ actions: false }}
                                    style={{ width: '100%' }}
                                />
                            </div>
                        ) : null}
                    </div>
                </div>

            ) : (
                /* ── Table view ── */
                <div ref={tableRef} className="border rounded-lg overflow-hidden bg-white shadow-sm animate-in fade-in duration-300">
                    <div className="overflow-x-auto">
                        <table className="min-w-full text-sm">
                            <thead className="bg-slate-50 border-b">
                                <tr>
                                    {result.columns.map((col, idx) => (
                                        <th key={idx} className="px-4 py-3 text-left font-medium text-slate-700 whitespace-nowrap">
                                            {col}
                                        </th>
                                    ))}
                                </tr>
                            </thead>
                            <tbody>
                                {currentRows.map((row, rowIdx) => (
                                    <tr key={rowIdx} className="hover:bg-slate-50 border-b last:border-0 transition-colors">
                                        {result.columns.map((col, cellIdx) => (
                                            <td key={cellIdx} className="px-4 py-3 text-slate-600 whitespace-nowrap">
                                                {getCellValue(row, col, cellIdx)}
                                            </td>
                                        ))}
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>

                    {totalPages > 1 && (
                        <div className="flex items-center justify-between px-4 py-3 bg-slate-50 border-t">
                            <div className="text-xs text-slate-500">
                                Showing {(currentPage - 1) * itemsPerPage + 1}–{Math.min(currentPage * itemsPerPage, result.rows.length)} of {result.rows.length}
                            </div>
                            <div className="flex gap-1">
                                <Button variant="outline" size="sm" className="h-7 w-7 p-0"
                                    onClick={() => handlePageChange(currentPage - 1)} disabled={currentPage === 1}>
                                    <ChevronLeft className="w-4 h-4" />
                                </Button>
                                <div className="flex items-center justify-center min-w-[2rem] text-xs font-medium">
                                    {currentPage} / {totalPages}
                                </div>
                                <Button variant="outline" size="sm" className="h-7 w-7 p-0"
                                    onClick={() => handlePageChange(currentPage + 1)} disabled={currentPage === totalPages}>
                                    <ChevronRight className="w-4 h-4" />
                                </Button>
                            </div>
                        </div>
                    )}
                </div>
            )}
        </div>
    );
};

export default ResultsTable;
